Add darkmode 1
aichner/company-homepage pull request #12
Opened 2020-05-07 13:29 UTC by LucaAllmaier

**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- Currently, the switch to change the darkmode has no functionality 

**What is the new behavior (if this is a feature change)?**
- The darkmode switch sets the darkmode to the localStorage
- The darkmode prop is distributed to the child components

**Other information**:
-

2020-05-07 13:45 UTC, Aichnerc requested changes
Should be okay to merge after those fixes.

2020-05-07 13:45 UTC, Aichnerc commented on src/App.js
> +  _handler = () => {
We no longer use `_` infront of local functions. Please rename to `handler`.

2020-05-07 13:45 UTC, Aichnerc commented on src/App.js
> +              <Footer darkMode={this.state.darkMode} handler={this._handler} />
Change it to `this.handler` to not break the program.

2020-05-07 13:45 UTC, Aichnerc commented on src/App.js
> +                  mode={this.state.darkMode}
The mode is no longer required to be passed on because everything happens within the App.js and Footer.

2020-05-07 13:45 UTC, Aichnerc commented on src/components/molecules/Footer/index.jsx
> +                checked={this.props.darkMode}
This is not a stateful switch. Implement a `componentDidMount` where you `this.setState({darkMode: this.props.darkMode ? true : false})` and use the state on the `checked` param.

2020-05-07 13:45 UTC, Aichnerc commented on src/components/organisms/sections/CallToAction/index.jsx
> +        className={this.props.darkMode ? "dark" : "light"}
This is no longer required once this component is a child of `<main>`.

2020-05-07 13:45 UTC, Aichnerc commented on src/components/organisms/sections/Services/index.jsx
> +      <section id="services" className={this.props.darkMode ? "dark" : "light"}>
This is no longer required once this component is a child of `<main>`.

2020-05-07 13:45 UTC, Aichnerc commented on src/components/organisms/sections/Trusted/index.jsx
> +      <div id="trusted" className={this.props.darkMode ? "dark" : "light"}>
This is no longer required once this component is a child of `<main>`.

2020-05-07 13:45 UTC, Aichnerc commented on src/components/pages/HomePage/index.jsx
> +          <Trusted darkMode={globalProps.darkMode} />
This is no longer required once this component is a child of `<main>`.

2020-05-07 15:22 UTC, Aichnerc approved these changes
Should be okay to merge.

2020-05-09 10:54 UTC, schettn requested changes
Should be ok after few changes

2020-05-09 10:54 UTC, schettn commented on src/App.js
> +  let mode = localStorage.getItem("mode");
Add new line.
Ref: https://github.com/snek-at/tonic/blob/master/STYLE_GUIDE.md

2020-05-09 10:54 UTC, schettn commented on src/App.js
> +    localStorage.setItem("mode", false);
Add new line because of logical separation.
Ref: https://github.com/snek-at/tonic/blob/master/STYLE_GUIDE.md

2020-05-09 10:58 UTC, schettn approved these changes
Great work Mr. Allmaier. 👩‍🎨

2020-05-09 10:59 UTC, merged