Improve branding a1
aichner/company-homepage pull request #25
Opened 2020-06-01 13:50 UTC by Aichnerc

**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Documentation (non-breaking change which adds documentation)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the new behavior (if this is a feature change)?**
- Fix dark mode "light card" bug (Assignees: @Aichnerc ) #3 
  + Behaviour before Pull Request:
Currently when switching to dark mode, the `light card` background is dark. Closes #22 
  + Behaviour after Pull Request:
The `light card` remains the white background even in dark mode. Closes #22 

**Other information**:
- The version has been updated +0.0.1 (patch).

2020-06-01 14:17 UTC, Aichnerc reviewed
LGTM 🛹

2020-06-02 07:35 UTC, LucaAllmaier approved these changes
Looks good.

2020-06-02 08:04 UTC, pinterid approved these changes
Looks good.

2020-06-02 08:46 UTC, kleberbaum approved these changes
Should be ok to merge.

2020-06-02 08:51 UTC, schettn requested changes
Nearly

2020-06-02 08:51 UTC, schettn commented on src/components/pages/BrandingPage/index.jsx
> +                    </div>*/}
Nah. Not the correct formatting

2020-06-02 09:35 UTC, schettn approved these changes
LGTM!

2020-06-02 09:35 UTC, merged